### ISSUE TITLE
Quitar archivos de src que no necesitamos

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#1]
En src tenemos muchos archivos que usamos para ir aprendiendo, sugiero moverlos a otro lado como por ejemplo "Ejercicios/src"

**Comment by javierajorge** [comment]
si tenemos archivos para probar ponerlos en carpeta test

**Comment by javierajorge** [comment]
src
- libs
- app
- test
- utils

**Comment by javierajorge** [comment]
armar rama playground 
limpiar rama principal
