### ISSUE TITLE
config view - backend

### ISSUE THREAD

**Issue by AnnieScigliano** [AnnieScigliano/Proyecto-Incubadora#104]
modificar archivo de configuracion para que incluya mas campos

- [x] agregar campos al json
- [ ] agregar metodos de set y get de las fechas
- [ ] agregar el set y get del incubation period
- [ ] set y get del hash
- [ ] pruebas unitarias para todo

json de ejemplo:
{"min_temperature":40,"max_temperature":50,"rotation_duration":3500000,"rotation_period":5000,"ssid":"mimimi","passwd":"1234", "tray_one_date": 1000000,"tray_two_date": 500000,"tray_three_date": 0,"incubation_period": 18,"hash": "12345"}

**Comment by javierbrk** [comment]
esto tambien es importante
