### ISSUE TITLE
Hardware y fierros Rotación

### ISSUE THREAD

**Issue by fabriciopetiso** [AnnieScigliano/Proyecto-Incubadora#111]
Ver insumos necesarios para replicar Rio4

**Comment by fabriciopetiso** [comment]
Ver insumos necesarios para replicar Rio4

**Comment by Pablomonte** [comment]
### Hardware PCB monitoreo
Conseguimos el diseño esquemático y PCB de una placa exclusivamente para monitoreo, centrado en manejar mayor cantidad de sensores o entradas de datos y sin salidas de control.
Faltarían elementos como:
- Estaño líquido en frío
- flux en aerosol
- Resistencias y capacitores SMD 0805:
 · R 10 k
 · R 330 ohm
 · C 10 ųf
 · C 0,1ųf
### Sistema Rotación
mostraron su [diseño](https://drive.google.com/file/d/1461bH8t6aSu1HC4yN-d4BafLo0HaI6z4/view?usp=drive_link) basado en una cinta (tipo persiana automática) asociada a las bandejas y a un contrapeso, para asegurar la bajada cuando la cinta se desenrolla.
Podríamos implementarlo sencillamente, [imprimiendo en 3D](https://drive.google.com/drive/folders/1nE6MwN6DniMfThNCMOiFd71PbD6T468f?usp=drive_link) la polea y portamotor. 
![Image](https://github.com/AnnieScigliano/Proyecto-Incubadora/assets/104506596/571c2800-df3f-4759-a052-5c65ee8e3452)
