### ISSUE TITLE
understand _G table use in modules

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#122]

**Comment by JereC4str0** [comment]
encontré algunos links interesantes sobre el tema:


https://devforum.roblox.com/t/what-is-g-and-for-what-i-can-use-it/322199

https://stackoverflow.com/questions/35910099/how-special-is-the-global-variable-g

https://forums.coregames.com/t/tutorial-how-to-use-global-functions-variables-to-simplify-development/1335
