### ISSUE TITLE
enviar los datos con timestamp

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#14]
Actualmente enviamos los datos y no nos fijamos si grafana esta en línea o no...
podemos guardar datos en memoria y enviarlos posteriormente. 

este comando envía datos con un timestamp a grafana

curl -i -XPOST 'http://grafana.altermundi.net:8086/write?db=cto' -u token:e98697797a6a592e6c886277041e6b95 --data-binary "mediciones,device=XX-bme280 temp=29,hum=60.00,press=800 1676515676854775806"

el time stamp se agrega separado por un espacio al final... 

1676515676854775806 nanosegundos desde 1970 corresponden  a 
Your time zone: Wednesday, February 15, 2023 11:47:56.854 PM [GMT-03:00](https://www.epochconverter.com/timezones?q=1676515676854775800)
se puede validar en "epochconverter"

es una buena idea verificar que la hora del dispositivo sea correcta
asegurarse de que se este usando el servicio de ntp 
agregar el time stamp al envío.

en otra instancia guardaremos en memoria algunos datos y los enviaremos cuando contemos con conectividad

**Comment by javierbrk** [comment]
este issue quedo colgado le metemos ?

**Comment by javierbrk** [comment]
ver que funciones devuelven la hora,
configurar el ntp 
el send to grafana agrega una marca de tiempo con la hora actual

**Comment by javierajorge** [comment]
usar esto una vez que tenemos internet
time.initntp("pool.ntp.org")
time.get()
desde la api rest podemos sincronizar la hora con 
time.set(1542678050)
debemos configurar la zona horaria 
time.settimezone("EST+5")
esto debería ir en un endpoint

**Comment by javierbrk** [comment]
creo que ya podemos cerrar este issue no ?
