### ISSUE TITLE
actualizar el readme indicando que archivos enviar al esp32 y como hacerlo con las tools mencionadas

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#18]
Tal vez lo mas facil sea indicar como subir los archivos necesarios para que funcione todo usando la tool del nodemcu

**Comment by Santiagocetran** [comment]
actualice el readme con los archivos que hay que correr para que el ESP se conecte al wifi y mande datos a grafana
