### ISSUE TITLE
framework de pruebas 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#38]
framework de pruebas 
api rest python server
pruebas en lua 
pruebas en flater

**Comment by Santiagocetran** [comment]
hola javi, no estariamos entendiendo muy bien este issue :)

**Comment by javierajorge** [comment]
tenemos la primer prueba interesante con busted y un código de ejemplo para aprender a escribirlas

**Comment by javierajorge** [comment]
https://github.com/AnnieScigliano/Proyecto-Incubadora/blob/8dc13fb1d2ef7a4fbf4af264feef35d1b6705d1b/src/test/test_big_busted_sample.lua

**Comment by javierajorge** [comment]
solo nos falta hacer un tallercito de tdd con esto !
