### ISSUE TITLE
hacer un scann cuando no puede conectarse a un wifi para que muestre las redes disponibles

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#4]
Suele suceder que configuramos una red nueva y a veces nos equivocamos de credenciales o la red esta muy lejos y el esp no la ve. 
Poner un scan cuando no puede conectarse permite ver las redes disponibles 
modificar el archivo initwifi.lua

**Comment by AnnieScigliano** [comment]
fixes #4

**Comment by javierbrk** [comment]
https://nodemcu.readthedocs.io/en/dev-esp32/modules/wifi/#wifistascan ver en la docu como hacer el scan sin que se rompa

**Comment by javierbrk** [comment]
para probarlo se puede configurar un wifi con credenciales erroneas .... luego de unos 10 intentos deberíamos ver el resultado del scan
