### ISSUE TITLE
ota

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#5]
pensar en ota
tener resuelto el fall back

**Comment by javierbrk** [comment]
@JereC4str0 podes colocar aquí el enlace sobre ota para empezar la discusión

**Comment by JereC4str0** [comment]
https://www.instructables.com/ESP8266-OTA-LUA-With-WEB-UI-MANAGEMENT-Nodemcu-Fir/

**Comment by JereC4str0** [comment]
https://unifiedpush.org/

**Comment by javierajorge** [comment]
https://github.com/nodemcu/nodemcu-firmware/tree/release/lua_examples/luaOTA creo que va por acá la cosa
