### ISSUE TITLE
Jere debe aprobar los pull request de cambios de firmware de la incubadora 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#52]
Jere debe aprobar los pull request de cambios de firmware de la incubadora 
ver si se puede forzar esa regla

**Comment by JereC4str0** [comment]
https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
