### ISSUE TITLE
repeticion larga de post, ¿Será esto un problema ? 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#59]
![image](https://github.com/AnnieScigliano/Proyecto-Incubadora/assets/4826216/1958fcf3-0767-4499-8f61-121cc7fcc875)

Esto podría ser un problema, deberia controlar 3 veces y enviar 1 ... son timers cada 3 s y cada 1 s 

temp actual  25.46 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=25.5,hum=27.5,press=808.78 1698694063000000000
true
temp actual  25.49 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  25.52 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  25.55 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=25.59,hum=27.38,press=808.73 1698694066000000000
true
temp actual  25.59 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  25.63 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  25.66 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=25.69,hum=27.26,press=808.68 1698694069000000000
true
temp actual  25.68 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  25.73 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  25.78 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=25.82,hum=27.14,press=808.75 1698694072000000000
true
temp actual  25.82 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  25.86 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  25.91 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
mediciones,device=IncuFa-bme temp=25.96,hum=26.98,press=808.71 1698694075000000000
true
temp actual  25.96 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  25.99 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.01 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.09,hum=26.96,press=808.71 1698694078000000000
true
temp actual  26.09 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.12 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.18 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.21,hum=26.64,press=808.7 1698694081000000000
true
temp actual  26.22 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.28 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.32 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.35,hum=26.44,press=808.58 1698694084000000000
true
temp actual  26.35 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.41 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.46 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.51,hum=26.26,press=808.66 1698694087000000000
true
temp actual  26.5 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.54 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.58 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.64,hum=26.13,press=808.56 1698694090000000000
true
temp actual  26.64 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.68 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.74 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.84,hum=25.96,press=808.66 1698694093000000000
true
temp actual  26.84 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  26.88 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  26.91 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=26.96,hum=25.67,press=808.61 1698694096000000000
true
temp actual  26.96 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  27.01 , max  38 ,min  37.5 ,resitor status  true
true
temp actual  27.13 , max  38 ,min  37.5 ,resitor status  true
mediciones,device=IncuFa-bme temp=27.19,hum=25.49,press=808.51 1698694099000000000
true
temp actual  27.2 , max  38 ,min  37.5 ,resitor status  true
HTTP POST return 204
true
temp actual  27.29 , max  38 ,min  37.5

**Comment by JereC4str0** [comment]
#### cambie el tiempo de control a 3 segundos y el de envio a 1 segundo 

link del [commit](https://github.com/JereC4str0/Proyecto-Incubadora/commit/8c25dacca581ef283c190401c051771e6d26620c)
