### ISSUE TITLE
mejorar los mensajes de log con marca de tiempo lejible 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#60]
Los logs no tienen marca de tiempo. 
Para poder entender los errores debemos mejorar los mensajes de error. 
Crear una funcion log que agregue marca de tiempo y nombre de la funcion 

Revisar todos los mensajes

**Comment by javierbrk** [comment]
Para loggear lo que sucede en las incubadoras a un archivo se puede usar screen 

```$sudo apt install screen```
crear un archivo en home que se llame .screenrc con este contenido


```
logfile /tmp/screenlog.$$
log on
deflog on
logtstamp on
```
lanzar el comando 
```screen /dev/ttyUSB0 115200 -L```

para finalizar el log se puede presionar las teclas 
"ctrl+a" luego "k" luego "y"

**Comment by fabriciopetiso** [comment]
Esto quedó implementado ahora en el prototipo. (Hay que cerrar el ESPlorer para que corra el screen, revisar el que ttyUSB coincida)

**Comment by JereC4str0** [comment]
### Otra forma de guardar los logs 

``` nodemcu-uploader --port dev/ttyUSB0 terminal > logs.txt &```

**Comment by javierbrk** [comment]
> ### Otra forma de guardar los logs
> 
> ` nodemcu-uploader --port dev/ttyUSB0 terminal > logs.txt &`
Esta buena la alternativa ! 

esta forma permite ver el log y guardarlo además ?  o solo guardarlo ?

**Comment by JereC4str0** [comment]
se podria usar el comando tee en linux,  para que escriba en la salida standar y en un archivo a la vez:
```nodemcu-uploader --port dev/ttyUSB0 terminal 2>&1 | tee -a logs.txt```
