### ISSUE TITLE
las variables de tiempo de rotacion, tiempo de monitoreo y tiempo de control deben ir a la  la configuración 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#67]
las variables de tiempo de rotacion, tiempo de monitoreo y tiempo de control deben ir a la  la configuración 
Todos los tiempos deben ser configurables pero no se pueden poner tiempos muy exigentes
los timers deben tener una guarda, y las funciones de configuracion de tiempos deben tener guardas para evitar el colapso

**Comment by JereC4str0** [comment]
a que te referís con "guarda" javi ?
