### ISSUE TITLE
agregar nuevo mensaje para enviara grafana que tenga el uptime y el heap y la frecuencia del micro y la temperatura del core 

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#68]

**Comment by fabriciopetiso** [comment]
Esto sería para seguir el problema de Brownout ? o algo más general?

**Comment by javierbrk** [comment]
> Esto sería para seguir el problema de Brownout ? o algo más general?

Es general para detectar reinicios desde grafana y un posible problema de falta de memoria. No creo que estemos en esa situacion hoy.  La temp del micro creo que puede influir

**Comment by JereC4str0** [comment]
este mensaje tiene que ir a un tablero diferente o como hacemos para adaptarlo al existente?

**Comment by JereC4str0** [comment]
### Logré crear un panel para el Heap y para el Uptime, pero no para la frecuencia del micro.

#### supuestamente añadieron una funcion para leer la frecuencia del gpu pero esta no aparece en la documentacion oficial

* dejo el [link](https://github.com/nodemcu/nodemcu-firmware/issues/2374) del issue en donde se menciona la funcíon node.cpufreq()
* usé este [modulo](https://nodemcu.readthedocs.io/en/dev-esp32/modules/node/)

#### tuve problemas a la hora de especificarle a grafana que mida el tiempo en minutos, solo logré dejarlo en ms, adjunto imagen de muestra
[![imagen.png](https://i.postimg.cc/90Gyw0TP/imagen.png)](https://postimg.cc/MfpnhW9X)

**Comment by JereC4str0** [comment]
abrí una pull request con esto #76

**Comment by javierbrk** [comment]
aca hay dos opciones

1. lo envias convertido desde la esp 
2. lo convertis agregando una opcion "math" en las query. En el tablero principal las estoy usando par ajustar los dos sensores

**Comment by javierbrk** [comment]
como viene esto ?
