### ISSUE TITLE
aprender a vincular issues y commits 

### ISSUE THREAD

**Issue by javierajorge** [AnnieScigliano/Proyecto-Incubadora#7]
https://docs.devart.com/studio-for-sql-server/source-controlling-databases/associating-commits-with-github-issues.html

**Comment by javierajorge** [comment]
https://docs.github.com/es/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by javierajorge** [comment]
Close
    Closes
    Closed
    Fix
    Fixes
    Fixed
    Resolve
    Resolves
    Resolved

**Comment by javierajorge** [comment]
![Screenshot from 2023-02-10 14-24-40](https://user-images.githubusercontent.com/77751165/218156793-2ee7bbbe-8df0-409a-9c0a-54cfbac69666.png)

**Comment by JereC4str0** [comment]
https://danielmaldonado.com.ar/programacion/como-cerrar-un-issue-en-github/

**Comment by javierbrk** [comment]
propongo usar fixes ... 
$ git commit -m "Nueva funcionalidad **Fixes #66**"
