### ISSUE TITLE
Agregar soporte para finales de carrera

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#74]
Debería tener una alerta que no esta rotando

**Comment by JereC4str0** [comment]
#### Esto es lo que interpreté
https://github.com/JereC4str0/Proyecto-Incubadora/commit/ac3e6657669a75c72d372e8ebb9c3149e5c273bf

**Comment by JereC4str0** [comment]
se me ocurre agregar [debajo de esta linea](https://github.com/AnnieScigliano/Proyecto-Incubadora/blob/5167734587ff0888ed441800fad196cdd8169e26/src/app/incubator.lua#L172)
una alerta como esta:

``` alerts.send_alert_to_grafana("[!] incubator is not rotating")```
