### ISSUE TITLE
por elmomento servir estaticamente todo el filesystem desde el web browser

### ISSUE THREAD

**Issue by javierbrk** [AnnieScigliano/Proyecto-Incubadora#86]
agregar un get para obtener json y otro para csv tipo estatico que muestre capturas de datos y el json de configuracion.

**Comment by JereC4str0** [comment]
```lua
httpd.static("config.json", "application/json")
```

httpd_uri: httpd_register_uri_handler: handler config.json with method 1 already registered

### Intente de esta forma pero me dice que ya tengo un metodo registrado, pero es la unica ruta estatica :crying_cat_face:
